"""
Slide styles seed data for OfficeMaker.
Contains 49 predefined slide styles for image generation.
"""

SLIDE_STYLES = [
    {
        "style_id": 1,
        "name": "벤토 그리드 스타일(모던 웹UI)",
        "name_en": "Bento Grid",
        "prompt": "Bento grid UI layout, tech minimalist design, clean web interface, soft lighting, modern corporate aesthetic, vector flat style, UI/UX --ar 16:9",
        "category": "modern",
        "is_active": True,
    },
    {
        "style_id": 2,
        "name": "비즈니스 미니멀 스타일",
        "name_en": "Business Minimal",
        "prompt": "Minimalist timeline infographic, simple flat vector art, clean data visualization, geometric shapes, corporate color palette, white background, highly legible --ar 16:9",
        "category": "business",
        "is_active": True,
    },
    {
        "style_id": 3,
        "name": "칠판 스타일 (교육용 슬라이드)",
        "name_en": "Chalkboard",
        "prompt": "Chalkboard sketch, educational diagram, white chalk on dark green board, hand-drawn aesthetic, arrows and mind maps, friendly and approachable tone",
        "category": "creative",
        "is_active": True,
    },
    {
        "style_id": 4,
        "name": "일본 종이 만화책 스타일",
        "name_en": "Manga",
        "prompt": "Manga instructional comic panel, clean line art, monochrome with screentones, informative speech bubbles, office worker character, tutorial style, expressive",
        "category": "creative",
        "is_active": True,
    },
    {
        "style_id": 5,
        "name": "뉴 모피즘 스타일 (모던 웹사이트)",
        "name_en": "Neumorphism",
        "prompt": "Neumorphic tech schematic, soft UI, drop shadows, subtle gradients, clean tech blueprint, modern app interface, minimalist 3D layout",
        "category": "modern",
        "is_active": True,
    },
    {
        "style_id": 6,
        "name": "바우하우스(현대 건축, 현대 미술) 스타일",
        "name_en": "Bauhaus",
        "prompt": "Bauhaus aesthetic, geometric abstraction, primary colors (red, blue, yellow), strict grid, modern minimalist poster, clean typography layout",
        "category": "artistic",
        "is_active": True,
    },
    {
        "style_id": 7,
        "name": "네온/사이버 펑크 스타일",
        "name_en": "Neon Cyberpunk",
        "prompt": "Neon noir technological scene, cyberpunk aesthetic, dark background with glowing neon accents, glowing data streams, highly detailed, futuristic",
        "category": "creative",
        "is_active": True,
    },
    {
        "style_id": 8,
        "name": "도스 스타일(터미널, 녹색 텍스트)",
        "name_en": "DOS Terminal",
        "prompt": "Retro CRT monitor screen, Matrix green text on black background, glowing phosphor, terminal code, vintage hacker aesthetic, scanlines",
        "category": "retro",
        "is_active": True,
    },
    {
        "style_id": 9,
        "name": "복셀(3차원 픽셀) 아트 스타일",
        "name_en": "Voxel Art",
        "prompt": "Isometric voxel art, gamified office environment, highly detailed blocks, bright lighting, colorful pixel 3D, cute architectural diagram --ar 16:9",
        "category": "creative",
        "is_active": True,
    },
    {
        "style_id": 10,
        "name": "클레이 애니메이션 스타일",
        "name_en": "Claymation",
        "prompt": "Claymation style, tactile 3D illustration, cute office worker figurine, soft smooth lighting, playful stop-motion aesthetic, vibrant pastel colors",
        "category": "creative",
        "is_active": True,
    },
    {
        "style_id": 11,
        "name": "식물학/과학 일러스트 스타일",
        "name_en": "Botanical Scientific",
        "prompt": "Botanical scientific illustration, vintage field guide style, delicate line work, watercolor shading, highly detailed and precise",
        "category": "artistic",
        "is_active": True,
    },
    {
        "style_id": 12,
        "name": "카와이 스타일 / 파스텔 톤",
        "name_en": "Kawaii Pastel",
        "prompt": "Kawaii illustration, girly pastel colors, soft and fluffy aesthetic, cute minimalist characters, warm lighting, dreamlike",
        "category": "creative",
        "is_active": True,
    },
    {
        "style_id": 13,
        "name": "레트로 팝 스타일",
        "name_en": "Retro Pop",
        "prompt": "Retro pop art, playful aesthetic, 1980s Memphis design, bold outlines, vibrant flat colors, dynamic composition, energetic",
        "category": "retro",
        "is_active": True,
    },
    {
        "style_id": 14,
        "name": "빈티지/액션 코믹스 스타일",
        "name_en": "Vintage Action Comics",
        "prompt": "Vintage action comic panel, 1960s comic book style, halftone dot textures, dramatic angles, bold typography, retro coloring",
        "category": "retro",
        "is_active": True,
    },
    {
        "style_id": 15,
        "name": "레트로 코믹 액션 블루프린트",
        "name_en": "Retro Comic Blueprint",
        "prompt": "Retro-comic action blueprint, technical schematic drawing mixed with vintage comic art, blue and white colors, dynamic mechanical details",
        "category": "retro",
        "is_active": True,
    },
    {
        "style_id": 16,
        "name": "역동적(하이 옥탄) 스타일 애니메이션",
        "name_en": "High-Octane Anime",
        "prompt": "High-octane anime style, intense dynamic action, speed lines, high energy, dramatic lighting, vivid colors, epic perspective",
        "category": "creative",
        "is_active": True,
    },
    {
        "style_id": 17,
        "name": "로코코(프랑스, 낭만적) 스타일",
        "name_en": "Rococo",
        "prompt": "Elegant Rococo style, romantic ornate aesthetic, soft pastel oil painting, intricate gold floral details, vintage luxury",
        "category": "artistic",
        "is_active": True,
    },
    {
        "style_id": 18,
        "name": "플랫 코퍼레이트 일러스트",
        "name_en": "Flat Corporate",
        "prompt": "Corporate flat illustration, Alegria style, modern tech startup blog art, simplified vector characters working in office, minimal background, bright professional colors --ar 16:9",
        "category": "business",
        "is_active": True,
    },
    {
        "style_id": 19,
        "name": "글래스 모피즘 3D (투명) 스타일",
        "name_en": "Glassmorphism 3D",
        "prompt": "3D glassmorphism icons, frosted glass UI elements, modern tech aesthetic, soft studio lighting, clean white background, high-end corporate presentation style",
        "category": "modern",
        "is_active": True,
    },
    {
        "style_id": 20,
        "name": "페이퍼 컷아웃 아트 스타일",
        "name_en": "Paper Cutout",
        "prompt": "Layered paper cutout art, conceptual office desk, soft shadows, pastel colored paper, clean and minimal storytelling, tactile texture --ar 16:9",
        "category": "artistic",
        "is_active": True,
    },
    {
        "style_id": 21,
        "name": "플랫 벡터 모션그래픽 스타일",
        "name_en": "Flat Vector Motion",
        "prompt": "Flat vector illustration, science channel aesthetic, vibrant deep space colors, clean minimalist background, educational infographic, highly detailed yet simplified --ar 16:9",
        "category": "modern",
        "is_active": True,
    },
    {
        "style_id": 22,
        "name": "시네마틱 우주 SF 다큐멘터리 스타일",
        "name_en": "Cinematic Sci-Fi",
        "prompt": "Cinematic 3D render of a space station orbiting a gas giant, hard sci-fi aesthetic, hyper-realistic, dramatic lighting, volumetric scattering, 8k resolution, space documentary style --ar 16:9",
        "category": "creative",
        "is_active": True,
    },
    {
        "style_id": 23,
        "name": "뉴스레터 에디토리얼",
        "name_en": "Newsletter Editorial",
        "prompt": "Magazine editorial layout, modern business newsletter, elegant serif typography, two-column grid, muted earth tone palette, professional photography style --ar 16:9",
        "category": "business",
        "is_active": True,
    },
    {
        "style_id": 24,
        "name": "스케치노트 스타일",
        "name_en": "Sketchnote",
        "prompt": "Sketchnote visual summary, hand-drawn icons and typography, black ink with color highlights, clean white background, educational mind map, conference note style --ar 16:9",
        "category": "creative",
        "is_active": True,
    },
    {
        "style_id": 25,
        "name": "그라디언트 모던 커버",
        "name_en": "Gradient Modern Cover",
        "prompt": "Abstract gradient background, modern corporate cover design, smooth color transitions, geometric light effects, premium minimalist aesthetic, clean title space --ar 16:9",
        "category": "modern",
        "is_active": True,
    },
    {
        "style_id": 26,
        "name": "도트 픽셀 아트 2D",
        "name_en": "Dot Pixel Art 2D",
        "prompt": "16-bit retro pixel art, 2D side-scrolling game scene, office worker character, bright saturated colors, nostalgic game UI elements, clean pixel grid --ar 16:9",
        "category": "retro",
        "is_active": True,
    },
    {
        "style_id": 27,
        "name": "SaaS 대시보드 인포그래픽",
        "name_en": "SaaS Dashboard",
        "prompt": "SaaS dashboard infographic, clean enterprise UI, cards and charts, modern workplace software aesthetic, white and blue corporate palette, minimal interface, high clarity, presentation-ready, vector UI illustration --ar 16:9",
        "category": "business",
        "is_active": True,
    },
    {
        "style_id": 28,
        "name": "Before / After 비교 카드형",
        "name_en": "Before After Card",
        "prompt": "Before and after comparison card layout, split screen infographic, clean corporate design, organized workflow transformation, minimal icons, white background, highly legible, business presentation style --ar 16:9",
        "category": "business",
        "is_active": True,
    },
    {
        "style_id": 29,
        "name": "화이트보드 전략 회의형 스타일",
        "name_en": "Whiteboard Strategy",
        "prompt": "Whiteboard strategy meeting illustration, office team planning around a board, sticky notes and diagrams, modern business environment, clean semi-flat illustration, collaborative and intelligent tone --ar 16:9",
        "category": "business",
        "is_active": True,
    },
    {
        "style_id": 30,
        "name": "카드 뉴스형 정보 요약",
        "name_en": "Card News",
        "prompt": "Card news style explainer, modular information blocks, bold headings, clean Korean social media editorial aesthetic, minimal icons, bright background, business-friendly visual summary --ar 16:9",
        "category": "business",
        "is_active": True,
    },
    {
        "style_id": 31,
        "name": "서류 / 리서치 데스크 스타일",
        "name_en": "Research Desk",
        "prompt": "Research desk visualization, laptop with multiple documents and notes, clean analytical workspace, modern office desk, papers, charts and highlights, soft daylight, realistic editorial illustration --ar 16:9",
        "category": "business",
        "is_active": True,
    },
    {
        "style_id": 32,
        "name": "데이터 스토리텔링/광고 포스터",
        "name_en": "Data Storytelling",
        "prompt": "Data storytelling poster, one key metric highlighted, clean chart-driven composition, modern corporate poster design, bold typography, minimal geometric elements, presentation-friendly --ar 16:9",
        "category": "business",
        "is_active": True,
    },
    {
        "style_id": 33,
        "name": "프리미엄 컨설팅 슬라이드 스타일",
        "name_en": "Premium Consulting",
        "prompt": "Consulting deck visual, premium business slide aesthetic, clean layouts, subtle corporate color palette, sharp icons, minimal data elements, strategy presentation style, polished and executive-friendly --ar 16:9",
        "category": "business",
        "is_active": True,
    },
    {
        "style_id": 34,
        "name": "협업툴 메시지형 비주얼",
        "name_en": "Collaboration Tool",
        "prompt": "Collaboration app scene, modern team messaging and document sharing interface, office productivity software aesthetic, clean floating windows, minimal UI, bright professional environment --ar 16:9",
        "category": "modern",
        "is_active": True,
    },
    {
        "style_id": 35,
        "name": "포스트잇 문제 해결 맵",
        "name_en": "Post-it Problem Map",
        "prompt": "Sticky note problem solving map, colorful structured note clusters, clean workshop board, office ideation process, modern facilitation aesthetic, highly legible, visual thinking style --ar 16:9",
        "category": "creative",
        "is_active": True,
    },
    {
        "style_id": 36,
        "name": "미니멀 라인 아트 다이어그램",
        "name_en": "Minimal Line Art",
        "prompt": "Minimalist line art diagram, simple continuous black lines on off-white background, step-by-step process, clean UI/UX elements, highly legible, professional and elegant",
        "category": "modern",
        "is_active": True,
    },
    {
        "style_id": 37,
        "name": "프리미엄 스톡 사진",
        "name_en": "Premium Stock Photo",
        "prompt": "Candid photography of a diverse corporate team reviewing a document together in a bright modern boardroom, authentic expression, shot on 35mm lens, shallow depth of field, soft natural lighting --ar 16:9",
        "category": "business",
        "is_active": True,
    },
    {
        "style_id": 38,
        "name": "핸드드로잉 노트북 필기",
        "name_en": "Hand-drawn Notebook",
        "prompt": "Hand-drawn notebook journal page, lined paper texture, ballpoint pen sketches and handwritten notes, casual margin doodles, highlighted key points, warm personal study aesthetic, authentic and relatable --ar 16:9",
        "category": "creative",
        "is_active": True,
    },
    {
        "style_id": 39,
        "name": "아이소메트릭 플랫 인포그래픽",
        "name_en": "Isometric Flat Infographic",
        "prompt": "Isometric flat vector infographic, clean technical illustration, modern office workflow, soft gradient colors, organized layered structure, white background, professional and highly legible --ar 16:9",
        "category": "business",
        "is_active": True,
    },
    {
        "style_id": 40,
        "name": "듀오톤 그래픽 스타일",
        "name_en": "Duotone Graphic",
        "prompt": "Duotone graphic design, two-tone color overlay on photography, bold modern contrast, Spotify cover art aesthetic, striking visual impact, clean composition, contemporary editorial style --ar 16:9",
        "category": "artistic",
        "is_active": True,
    },
    {
        "style_id": 41,
        "name": "스텝 바이 스텝 매뉴얼",
        "name_en": "Step by Step Manual",
        "prompt": "Step-by-step instruction manual, IKEA assembly guide aesthetic, numbered sequential diagrams, simple line icons with color highlights, clean white background, universal pictogram style, highly functional and legible --ar 16:9",
        "category": "business",
        "is_active": True,
    },
    {
        "style_id": 42,
        "name": "3D 아이소메트릭 비즈니스 스타일",
        "name_en": "3D Isometric Business",
        "prompt": "3D isometric illustration, modern corporate workflow, clean office environment, soft clay render style, pastel and white color palette, highly detailed, soft studio lighting, tech business concept --ar 16:9",
        "category": "business",
        "is_active": True,
    },
    {
        "style_id": 43,
        "name": "모던 다크 모드 디자인",
        "name_en": "Modern Dark Mode",
        "prompt": "Sleek dark mode UI presentation background, subtle glowing gradients, deep black and dark gray palette, modern minimalist tech aesthetic, elegant and premium corporate style, clean negative space --ar 16:9",
        "category": "modern",
        "is_active": True,
    },
    {
        "style_id": 44,
        "name": "디지털 마인드맵 / 노드 스타일",
        "name_en": "Digital Mind Map",
        "prompt": "Abstract digital node network, glowing connecting lines and dots, clean data visualization concept, mind map aesthetic, modern deep tech background, soft glowing lights --ar 16:9",
        "category": "modern",
        "is_active": True,
    },
    {
        "style_id": 45,
        "name": "볼드 타이포그래피",
        "name_en": "Bold Typography",
        "prompt": "Bold typography poster design, Swiss style layout, massive clean sans-serif text layout, high contrast minimal colors, modern graphic design aesthetic, strong visual impact --ar 16:9",
        "category": "artistic",
        "is_active": True,
    },
    {
        "style_id": 46,
        "name": "폴라로이드 무드보드",
        "name_en": "Polaroid Moodboard",
        "prompt": "Polaroid scrapbook layout on a wooden desk, aesthetic moodboard, sticky notes, scattered paper clips, candid team moments, warm soft lighting, nostalgic yet professional editorial style --ar 16:9",
        "category": "creative",
        "is_active": True,
    },
    {
        "style_id": 47,
        "name": "디지털 태블릿 다이어리",
        "name_en": "Digital Tablet Diary",
        "prompt": "Digital planner interface, iPad GoodNotes aesthetic, pastel highlighters, digital handwriting, habit tracker layout, cozy personal productivity workspace, clean minimal design --ar 16:9",
        "category": "creative",
        "is_active": True,
    },
    {
        "style_id": 48,
        "name": "스위스 그리드 인포디자인",
        "name_en": "Swiss Grid Info Design",
        "prompt": "Swiss grid editorial design, ultra-clean modular layout, structured typography, asymmetric grid, modernist corporate poster, restrained color palette, highly legible, presentation-ready --ar 16:9",
        "category": "business",
        "is_active": True,
    },
    {
        "style_id": 49,
        "name": "포털형 카드 매거진",
        "name_en": "Portal Card Magazine",
        "prompt": "Portal-style card magazine layout, clean Korean editorial web design, modular content cards, bold headlines, soft neutral palette, user-friendly information hierarchy, modern media aesthetic --ar 16:9",
        "category": "business",
        "is_active": True,
    },
]
